org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.250
loader_version_range=[1,)
mod_id=sworddisplay
mod_name=Sword Displays
mod_license=GNU Lesser General Public License v3.0
mod_version=1.21.1-1.0.0-neo
mod_group_id=com.sofodev.sworddisplay
mod_authors=SoFoDev
mod_description=Allows the user to display their swords via the use of a sword display block.
